### ISSUE TITLE
Please add support for Windows ARM64

### ISSUE THREAD

**Issue by seflerZ** [Ruben2776/PicView#109]
**Describe the solution you'd like**
Enable Windows ARM64 support. Current release doesn't run on ARM cpu.

**Additional context**
Although Windows 11 can run X64 applications, it's not efficient.

**Comment by Ruben2776** [comment]
I have added new arm 64 releases at https://sourceforge.net/projects/picview/files/1.8.6/ however I do not have any device to test if it works

**Comment by seflerZ** [comment]
Thanks a lot. I've tested it with my Surface Pro X and it works great! The only question is how can I make it my default image viewer?

**Comment by Ruben2776** [comment]
If you have it installed from the installer, then you can delete all the files there and replace them with the new version. Otherwise you can select it as default photo viewer https://www.howtogeek.com/746203/how-to-set-your-default-apps-on-windows-11/

**Comment by seflerZ** [comment]
Tried but it keeps loading all the time. The strange thing is: when I specifically open a file from the program it works, but open images through default way, it keeps loading. I don't know if it is a problem of such ARM64 package introduced since I can't run the X64 version. 🤔

**Comment by seflerZ** [comment]
Tried the latest binary, it works now.

**Comment by ArminiusTux** [comment]
Eagerly awaiting ARM64 builds of [PicView 2.0](https://github.com/Ruben2776/PicView/releases/tag/2.0).😉

For some reason [PicView 1.9.6](https://github.com/Ruben2776/PicView/releases/tag/1.9.6)  turned out to be a x64 build. 
<img width="309" alt="PicView" src="https://github.com/Ruben2776/PicView/assets/44533868/9116cec2-1f3a-483f-b63b-a6bc76fe98b8">

Version 1.9.5 is fine though.
![grafik](https://github.com/Ruben2776/PicView/assets/44533868/a0d2a2f9-353d-4add-b1f0-d5f2c2ab3589)

**Comment by Ruben2776** [comment]
I'm sorry for the inconvenience. It doesn't build a release publish after the .NET 8 update. 
Can I make you download this and report to me if it works?
https://sourceforge.net/projects/picview/files/2.0/PicView%202.0%20arm64.zip/download

**Comment by ArminiusTux** [comment]
Dear @Ruben2776 , thank you for the kind words and the quick reply.

Your ARM64 testbuild of PicView v2.0 is working so far (tested the effects for instance).
![grafik](https://github.com/Ruben2776/PicView/assets/44533868/9930d82c-fc83-41f5-9132-0271a85f8a16)

I will therefor add your neat tool to this list of native Windows ARM-apps soon.
https://armrepo.ver.lt/

Last but not least, is there a way to reduce the overall filesize (300mb is a bit heavy)?
Getting rid of the "runtimes" subdirectory (because I already have the[ .NET runtimes](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) installed) was counterproductive. 😎

Regards

**Comment by Ruben2776** [comment]
Thank you very much.
I have figured out the issue that prevented me from publishing to arm64.
Additionally, I made a mistake. If you browse the files, you will see a folder named `publish`, which is the correct folder, and you should delete the other files since it doubles it. Sorry about that. 

I have updated the release to add the arm64 versions.
You can download the one without the runtime here https://github.com/Ruben2776/PicView/releases/download/2.0/PicView.2.0.NET.8.required.win-arm64.zip

**Comment by ArminiusTux** [comment]
Many thanks @Ruben2776 , I think you can close this issue and also #112 .
