### ISSUE TITLE
Images not centered

### ISSUE THREAD

**Issue by vivadavid** [Ruben2776/PicView#47]
Hi, I used PicView for the first time yesterday and I've noticed that images are not displayed centered.

Normally the image is placed on the left side of the screen, at a certain distance from the top:

![PicView 1](https://user-images.githubusercontent.com/9334287/135416811-a0754cc1-4de2-4011-a3f9-331bcaf18085.png)

In some cases, the image is placed on the top:

![PicView 2](https://user-images.githubusercontent.com/9334287/135416975-1ec3bf49-8443-4fd4-9beb-014ac354a2eb.png)

Occasionally, the image is cut out:

![PicView 3](https://user-images.githubusercontent.com/9334287/135417530-16be5788-d3e0-4c70-8926-6142c7834a56.png)

My preference would be for the images to be displayed both horizontally and vertically centered, but it would be nice if other options were available for users. For example, it might be useful to display the images justified to the top left, as this way the first pixel of each image would be exactly at the same position.

I hope you find this feedback useful to you. Thanks and keep up the good work!

**Comment by Ruben2776** [comment]
Hi there, thanks for reaching out.

The issue is caused because you've set the scaling in Windows settings to a value other than 100%, which caused the calculations to be different. 

To remedy this issue, you can turn off the _Stay Centered_ options in the settings window, by pressing `F4` .

I'll try and code in a solution that supports when Windows scaling is increased in the next release.

If you want the window to be at a certain position, just drag it around while holding `Shift` and set the _Auto fit window_ off by pressing `3`

**Comment by vivadavid** [comment]
Thank you for your quick reply!

You were right: my screen is rescaled.

1. I turned off "Keep window centered", but more images were cut out.
2. As for "Auto Fit", images get unnecessarily resized because they are smaller than the screen resolution.

**Comment by vivadavid** [comment]
If you don't mind me comparing PicView with other programmes, I was expecting a behaviour similar to the one you find in QuickLook, where all images are horizontally and vertically centered. You may want to have a look at it, as it's a great programme to preview all kinds of formats:

https://github.com/QL-Win/QuickLook

**Comment by Ruben2776** [comment]
It does keep things centered if you have default settings in PicView and set scaling to 100% in Windows settings though.

As for images getting cut out, I can't reproduce that.

I'm not sure what you mean by images getting unnecessarily resized because they are smaller than the screen resolution. The lowest size they can be resized to is the image resolution, if it's lower than your screen resolution.

**Comment by vivadavid** [comment]
What I mean is that all the images displayed earlier on my PC (with Auto Fit off) were small enough to fit the screen, and yet some were being resized to make them smaller.

It might be related to the reescale issue, so I'll wait for a future release. Thanks!

**Comment by Ruben2776** [comment]
Could I have you give this one a try and see if it fixes it?
https://sourceforge.net/projects/picview/files/PicView%20dpi%20center%20test.zip/download

**Comment by vivadavid** [comment]
Hi! Despite "Keep window centered" being on, images usually stay on the left of the screen and are occasionally cut out.

I think it works the same as in the previous version, but I'll try to test it again when it's not so late and I'm a bit more focused.

**Comment by vivadavid** [comment]
Hi, again! I thought the best thing would be to record a video

https://user-images.githubusercontent.com/9334287/135530108-cc25f1e9-3e5b-447c-9e32-8ee1d5f4a204.mp4

.

**Comment by Ruben2776** [comment]
Hi again, thanks for the video.

The issue is caused by the Windows operating system using its own algorithm on top of my coded in DPI settings. I remember it worked in an earlier version, but I think Windows updates might have caused the issue. Not entirely sure how to fix it with programming.

A solution you could use would be to right click `PicView.exe` in the file explorer and tick the override high DPI scaling tickbox as illustrated in pic:
![image](https://user-images.githubusercontent.com/4200419/135557160-d5b446d4-7c64-4831-aa1b-e0fdf510c8fe.png)

The application itself is DPI-aware to an extent, so it will still resize itself appropriately to your screen. I'll try to see if I can figure something out so this is not needed.

**Comment by vivadavid** [comment]
Hi! I've changed the settings and it worked! Thanks!
